---
abstract: 'Infrastructure plugin for the Catalyst'
author:
  - 'Yuval Kogman, C<nothingmuch@woobling.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Authentication
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Session: 0.10
  Catalyst::Runtime: 0
  Class::Inspector: 0
  MRO::Compat: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.10012
