--- #YAML:1.0
name:                Catalyst-Plugin-Authentication
version:             0.09999_01
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Catalyst:                      5.49
    Catalyst::Plugin::Session:     0.10
    Class::Inspector:              0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
